/**
 * Tests for urlHelpers.js
 */

import { runner, assert } from './test-framework.js';
import { getDefaultBranchURL, getRawContentURL } from './urlHelpers.js';

// Test getDefaultBranchURL
runner.test('getDefaultBranchURL: converts raw URL to display URL with default branch', () => {
    const template = {
        id: 'owner/repo/path/to/template.yaml',
        raw_url: 'https://raw.githubusercontent.com/owner/repo/main/path/to/template.yaml'
    };
    const result = getDefaultBranchURL(template);
    assert.equal(result, 'https://github.com/owner/repo/blob/main/path/to/template.yaml');
});

runner.test('getDefaultBranchURL: returns empty string if no raw_url', () => {
    const template = {
        id: 'owner/repo/template.yaml'
    };
    const result = getDefaultBranchURL(template);
    assert.equal(result, '');
});

runner.test('getDefaultBranchURL: converts raw URL with branch name', () => {
    const template = {
        id: 'owner/repo/template.yaml',
        raw_url: 'https://raw.githubusercontent.com/owner/repo/main/template.yaml'
    };
    const result = getDefaultBranchURL(template);
    assert.equal(result, 'https://github.com/owner/repo/blob/main/template.yaml');
});

runner.test('getDefaultBranchURL: handles deep nested paths', () => {
    const template = {
        id: 'lima-vm/lima/examples/alpine.yaml',
        raw_url: 'https://raw.githubusercontent.com/lima-vm/lima/master/examples/alpine.yaml'
    };
    const result = getDefaultBranchURL(template);
    assert.equal(result, 'https://github.com/lima-vm/lima/blob/master/examples/alpine.yaml');
});

/**
 * NOTE: Tests for getGitHubSchemeURL() have been removed.
 *
 * GitHub scheme URLs are now generated by the backend using Lima's library.
 * The backend tests cover this functionality in pkg/combiner/combiner_test.go.
 */

// Test getRawContentURL
runner.test('getRawContentURL: converts blob URL to raw URL', () => {
    const url = 'https://github.com/owner/repo/blob/main/template.yaml';
    const result = getRawContentURL(url);
    assert.equal(result, 'https://raw.githubusercontent.com/owner/repo/main/template.yaml');
});

runner.test('getRawContentURL: handles commit SHA URLs', () => {
    const url = 'https://github.com/owner/repo/blob/abc123def456abc123def456abc123def456abc1/template.yaml';
    const result = getRawContentURL(url);
    assert.equal(result, 'https://raw.githubusercontent.com/owner/repo/abc123def456abc123def456abc123def456abc1/template.yaml');
});

runner.test('getRawContentURL: handles nested paths', () => {
    const url = 'https://github.com/lima-vm/lima/blob/master/examples/alpine.yaml';
    const result = getRawContentURL(url);
    assert.equal(result, 'https://raw.githubusercontent.com/lima-vm/lima/master/examples/alpine.yaml');
});
