/**
 * URL generation utilities for GitHub and Lima URLs
 */

/**
 * Get URL with default branch instead of commit SHA
 * Uses the raw_url field to construct the display URL with default branch
 * @param {Object} template - Template object with raw_url field
 * @returns {string} URL with default branch
 */
export function getDefaultBranchURL(template) {
    // Convert raw_url to display URL
    // From: https://raw.githubusercontent.com/owner/repo/branch/path
    // To: https://github.com/owner/repo/blob/branch/path
    if (!template.raw_url) {
        console.error('Template missing raw_url field:', template.id);
        return '';
    }

    // Parse the raw URL
    // Format: https://raw.githubusercontent.com/OWNER/REPO/BRANCH/PATH
    const rawPattern = /^https:\/\/raw\.githubusercontent\.com\/([^\/]+)\/([^\/]+)\/([^\/]+)\/(.+)$/;
    const match = template.raw_url.match(rawPattern);

    if (match) {
        const [, owner, repo, branch, path] = match;
        return `https://github.com/${owner}/${repo}/blob/${branch}/${path}`;
    }

    console.error('Could not parse raw_url:', template.raw_url);
    return '';
}

/**
 * NOTE: getGitHubSchemeURL() has been removed.
 *
 * GitHub scheme URLs are now generated by the backend using Lima's library,
 * which properly handles symlinks, redirects, and edge cases.
 *
 * The pre-generated URL is available in template.github_url from catalog.jsonl.
 */

/**
 * Convert GitHub blob URL to raw content URL
 * @param {string} url - GitHub blob URL
 * @returns {string} Raw content URL
 */
export function getRawContentURL(url) {
    let rawURL = url.replace('github.com', 'raw.githubusercontent.com');
    rawURL = rawURL.replace('/blob/', '/');
    return rawURL;
}
